
export const INCREMENT_COUNTER = "INCREMENT_COUNTER";
export const DECREMENT_COUNTER = "DECREMENT_COUNTER";

export const GET_MEDICINES = "GET_MEDICINES";
export const DELETE_MEDICINE = "DELETE_MEDICINE";
export const ADD_MEDICINES = "ADD_MEDICINES";
export const UPDATE_MEDICINES = "UPDATE_MEDICINES";
export const LOADING_MEDICINES = "LOADING_MEDICINES";

export const GET_DEPARTMENTS = "GET_DEPARTMENTS"
export const DELETE_DEPARTMENTS = "DELETE_DEPARTMENTS"
export const ADD_DEPARTMENTS = "ADD_DEPARTMENTS"
export const UPDATE_DEPARTMENTS = "UPDATE_DEPARTMENTS"


